apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nodejs
  name: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs
    spec:
      volumes:
      - name: nodejs-config-volume
        configMap:
          name: nodejs-config
      containers:
      - image: dmakeroam/nodejs:1.0.0-beta
        name: nodejs
        ports:
        - name: "tcp"
          protocol: TCP
          containerPort: 8080
        resources: {}
        volumeMounts:
          - name: nodejs-config-volume
            mountPath:  /usr/src/app/.env
            subPath: .env
status: {}
